---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-webapp-elasticweb-operator-v1-elasticweb
  failurePolicy: Fail
  name: melasticweb.kb.io
  rules:
  - apiGroups:
    - webapp.elasticweb-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elasticwebs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-webapp-elasticweb-operator-v1-nodepool
  failurePolicy: Fail
  name: mnodepool.kb.io
  rules:
  - apiGroups:
    - webapp.elasticweb-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodepools
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-webapp-elasticweb-operator-v1-elasticweb
  failurePolicy: Fail
  name: velasticweb.kb.io
  rules:
  - apiGroups:
    - webapp.elasticweb-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - elasticwebs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-webapp-elasticweb-operator-v1-nodepool
  failurePolicy: Fail
  name: vnodepool.kb.io
  rules:
  - apiGroups:
    - webapp.elasticweb-operator
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodepools
  sideEffects: None
