# permissions for end users to view nodepools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodepool-viewer-role
rules:
- apiGroups:
  - webapp.elasticweb-operator
  resources:
  - nodepools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - webapp.elasticweb-operator
  resources:
  - nodepools/status
  verbs:
  - get
