apiVersion: webapp.elasticweb-operator/v1
kind: NodePool
metadata:
  name: master
spec:
  taints:
    - key: node-pool.webapp.elasticweb-operator
      value: master
      effect: NoSchedule
  labels:
    "node-pool.webapp.elasticweb-operator/master": "8"
  handler: runc